### ISSUE TITLE
Capture only part of screen, Highlight QR codes

### ISSUE THREAD

**Issue by ilyavitek** [kefniark/UnityBarcodeScanner#26]
Can I now scan only part of webcam view? (I am trying to work with it and hololens and would like to scan only "center".

**Comment by kefniark** [comment]
No that's not possible right now.

After it's possible to hack around in `Webcam.cs` https://github.com/kefniark/UnityBarcodeScanner/blob/master/Assets/Scripts/Webcam/UnityWebcam.cs#L66
And filter / modify this array of pixel to obtain exactly the result you expect.
But because all that processing happen on the CPU, performance will probably not be that great.

Image processing it totally out of the scope of this project.

**Comment by kefniark** [comment]
Sending me message on twitter will not change my answer :)

**Comment by ilyavitek** [comment]
Thank you! It will be great if there will be some functional to "highlight" detected QR code.

**Comment by kefniark** [comment]
Ha ok, that one sounds like a doable feature request.
I will add it to my feature wish-list.
