### ISSUE TITLE
Camera stuck on scene change

### ISSUE THREAD

**Issue by johnymachine** [kefniark/UnityBarcodeScanner#37]
Is there any way to implement stoping camera on scene destroy?

I use this code and it works fine:
```csharp
	public IEnumerator StopCamera(Action callback)
	{
		// Stop Scanning
		Image = null;
		BarcodeScanner.Destroy();
		BarcodeScanner = null;
		// Wait a bit
		yield return new WaitForSeconds(0.1f);
		callback.Invoke();
	}
```

But if I change scene from menu (different scene as overlay with dynamic content references to other scenes) using SceneManager my camera gets stuck until closing Unity editor.

Would you be so kind to suggest any solution? I dont want to drag refrence to camera everywhere just to make sure it closes or reimplement scene manager... =(

**Comment by kefniark** [comment]
hum sadly there is not much here to do except asking unity to fix this issue.
As the comment explain: http://forum.unity3d.com/threads/closing-scene-with-active-webcamtexture-crashes-on-android-solved.363566/
it cause unity crash if you don't close the camera manually first and wait a bit 😞 

This bug is there since years (it was already causing problem in unity 5.3), if you find any better idea I'm sure lot of people would be interested

**Comment by johnymachine** [comment]
For now Quick&Dirty fix: I find ScannerController script and call its public method StopCamera() and change scene after that...

Did not find better way to cleanup automaticly. =( OnDestroy, IDisposable did not work either...

I was thinking on extending SceneManager with event BeforeSceneChange...

Thanks for quick reply!
